registerPresentation(17, 'A', 'Reforzamiento Transversal A y B', [
    { tipo: "titulo", modulo: "A+B", titulo: "Reforzamiento Transversal", subtitulo: "Día 17 — Velocidad e Integración para CENEVAL" },
    { tipo: "contenido", titulo: "Objetivo del Día 17", contenido: "<p>Hoy nos enfocamos en el reconocimiento de patrones de error bajo presión cronometrada.</p><ul><li>Trucos de concordancia (Sujeto Colectivo)</li><li>Nexos lógicos y cohesión adversativa</li><li>Cálculo rápido de probabilidad complementaria</li><li>Análisis de gráficos engañosos</li></ul>" },
    { tipo: "concepto", titulo: "Sujetos Colectivos", frente: "¿Cómo concuerda el verbo con sustantivos como 'jauría' o 'grupo' seguidos de complementos en plural?", reverso: "Siempre en SINGULAR. El verbo concuerda con el núcleo del sujeto (grupo, jauría, coalición)." },
    { tipo: "ejemplo", titulo: "Gramática en Contexto Electoral", contenido: "<p><b>Incorrecto (Trampa común):</b> El grupo de observadores internacionales <i>presentaron</i> el informe.</p><p><b>Correcto:</b> El grupo de observadores internacionales <i>presentó</i> el informe.</p>" },
    { tipo: "quiz", titulo: "Prueba Rápida de Concordancia", pregunta: "La documentación oficial, junto con las urnas adicionales, ____ enviada en el camión.", opciones: ["A) fueron", "B) fue", "C) han sido"], respuesta: 1, feedbackOk: "¡Correcto! El sujeto principal es 'La documentación' (singular).", feedbackError: "Recuerda: 'junto con las urnas' es maquillaje. El núcleo es 'La documentación'." },
    { tipo: "contenido", titulo: "Nexos Adversativos", contenido: "<p>Indican oposición o contraste frente a la idea anterior.</p><ul><li>Sin embargo</li><li>No obstante</li><li>Por el contrario</li></ul><p>Regla del CENEVAL: Si la segunda frase invalida total o parcialmente la primera, el conector debe ser adversativo.</p>" },
    { tipo: "ejemplo", titulo: "Nexos en el Examen", contenido: "<p><b>Reactivo:</b> La sesión del consejo cumplió con los tiempos; __________, el representante apeló la resolución.</p><p><b>Respuesta lógica:</b> <i>sin embargo</i> (porque apelar rompe la armonía del cumplimiento).</p>" },
    { tipo: "concepto", titulo: "Probabilidad por Complemento", frente: "¿Cuándo usar el complemento 1 - P(A)?", reverso: "Cuando el CENEVAL pregunta la probabilidad de que 'NO' suceda un evento o que ocurra 'Al menos uno'. Es más rápido calcular lo opuesto y restarlo." },
    { tipo: "formula", titulo: "Fórmula de Laplace y Complemento", formula: "P(A) = Casos Favorables / Casos Totales\nP(No A) = 1 - P(A)", explicacion: "Si la probabilidad de que una casilla abra a tiempo es de 3/4, la probabilidad de que NO abra a tiempo es 1 - 3/4 = 1/4." },
    { tipo: "quiz", titulo: "Cálculo Rápido", pregunta: "En una urna hay 10 votos nulos de un total de 50. Si sacas uno al azar, ¿cuál es la probabilidad de que NO sea nulo?", opciones: ["A) 20%", "B) 80%", "C) 10%"], respuesta: 1, feedbackOk: "¡Así se hace! La prob de nulo es 10/50 = 20%. El complemento es 100% - 20% = 80%.", feedbackError: "Calculaste la probabilidad de que sí fuera nulo, te pidieron el complemento." },
    { tipo: "contenido", titulo: "Lectura Analítica de Gráficos", contenido: "<p>Los engaños visuales más letales en el Módulo B:</p><ul><li><b>Ejes truncados:</b> La gráfica empieza en un número distinto de 0 para exagerar la diferencia visual.</li><li><b>Escalas ignoradas:</b> Barras que miden 'miles' pero el evaluado las lee como valores absolutos.</li><li>Siempre lee el texto de los ejes antes de ver las barras.</li></ul>" },
    { tipo: "ejemplo", titulo: "Histogramas Electorales", contenido: "<p>Si te piden comparar el crecimiento de un partido entre 2012 y 2018, busca el número exacto etiquetado en la barra, no te fíes de si 'se ve el doble de grande'.</p>" },
    { tipo: "concepto", titulo: "Teoría de Conjuntos en Segundos", frente: "¿Cómo calculas cuántos saben hacer 'Ambas Cosas' si te dan los que saben A, los que saben B, el Total y los que saben Ninguna?", reverso: "Ambos = (A + B) - (Total - Ninguno)." },
    { tipo: "quiz", titulo: "Aplica la Fórmula", pregunta: "De 100 personas, 20 no saben nada. 60 saben A y 50 saben B. ¿Cuántos saben ambas?", opciones: ["A) 30", "B) 10", "C) 20"], respuesta: 0, feedbackOk: "Total real (80). 60+50 = 110. 110 - 80 = 30. ¡Perfecto!", feedbackError: "Repasa la fórmula: sumas los individuales y le restas el universo activo." },
    { tipo: "resumen", titulo: "Puntos clave del día", puntos: ["Cuidado con el maquillaje en sujetos gramaticales.", "Dominar el nexo es dominar la cohesión.", "El complemento probabilístico ahorra minutos críticos.", "El texto manda sobre el dibujo en los gráficos.", "A + B - (Total - Ninguno) = Intersección."] }
]);
