registerPresentation(21, 'C', 'Constitucion: Arts. 39-41, 99 y 116 — Soberania y Sistema Electoral', [

    { tipo: "titulo", modulo: "C", titulo: "Constitucion: Arts. 39-41, 99 y 116", subtitulo: "Dia 21 — Soberania, Forma de Gobierno y Nucleo del Sistema Electoral" },

    { tipo: "contenido", titulo: "¿Por que estos 5 articulos son el cimiento?", contenido: "<p>Los articulos 39, 40, 41, 99 y 116 forman la <b>columna vertebral constitucional</b> de todo el sistema electoral mexicano.</p><ul><li><b>Art. 39:</b> ¿De donde viene el poder? Del pueblo.</li><li><b>Art. 40:</b> ¿Como se organiza ese poder? En una republica representativa, democratica, laica y federal.</li><li><b>Art. 41:</b> ¿Quien organiza las elecciones? El INE. ¿Que son los partidos? Entidades de interes publico.</li><li><b>Art. 99:</b> ¿Quien resuelve disputas electorales? El TEPJF.</li><li><b>Art. 116:</b> ¿Y en los estados? Los OPLEs, bajo supervision del INE.</li></ul>" },

    { tipo: "concepto", titulo: "Articulo 39 — Soberania Popular", frente: "¿Como define el articulo 39 a la soberania nacional?", reverso: "La soberania nacional reside ESENCIAL y ORIGINARIAMENTE en el pueblo.\n- Esencial: es propiedad intrinseca del pueblo, inseparable de el.\n- Originariamente: el origen del poder esta en el pueblo, no en el gobierno.\n- El pueblo puede alterar su forma de gobierno en todo tiempo." },

    { tipo: "formula", titulo: "Articulo 40 — Los 4 adjetivos de Mexico", formula: "REPRESENTATIVA → ciudadanos eligen representantes\nDEMOCRATICA → poder descansa en la voluntad popular\nLAICA → separacion Estado-iglesias\nFEDERAL → estados autonomos en federacion\n\nOrden obligatorio: Rep. Dem. Laica Federal", explicacion: "El CENEVAL cambia 'laica' por 'religiosa' o 'federal' por 'unitaria'. Memoriza el orden exacto del articulo 40." },

    { tipo: "quiz", titulo: "Test Articulo 40", pregunta: "Segun el articulo 40, Mexico se constituye como una Republica...", opciones: ["A) Representativa, democratica, religiosa y federal.", "B) Representativa, democratica, laica y federal.", "C) Presidencial, democratica, laica y unitaria."], respuesta: 1, feedbackOk: "Correcto. El texto literal es: 'representativa, democratica, laica y federal'. Laica (no religiosa) y federal (no unitaria).", feedbackError: "El articulo 40 dice exactamente 'representativa, democratica, laica y federal'. La trampa clasica cambia 'laica' por 'religiosa' (A) o 'federal' por 'unitaria' (C)." },

    { tipo: "contenido", titulo: "Articulo 41 Base I — Los Partidos Politicos", contenido: "<p>Los partidos son <b>entidades de interes publico</b>. Ni empresas, ni organismos del Estado.</p><p><b>Finalidades constitucionales:</b></p><ul><li>Promover la participacion del pueblo en la vida democratica</li><li>Fomentar el principio de paridad de genero</li><li>Contribuir a la integracion de los organos de representacion politica</li></ul><p><b>Prerrogativas:</b> financiamiento publico, acceso a radio/TV, espacios para reuniones.</p><p><b>Obligaciones:</b> transparencia, rendicion de cuentas, paridad en candidaturas.</p>" },

    { tipo: "formula", titulo: "Art. 41 Base II — Formula de Financiamiento", formula: "TOTAL = 30% igualitario + 70% proporcional\n\n30% ÷ numero de partidos = parte igual por partido\n70% × (votos partido / votos totales) = parte proporcional\n\nPartido con 50% de votos en financiamiento de $800M:\n30%=$240M ÷ 4 partidos = $60M\n70%=$560M × 50% = $280M\nTOTAL = $340M", explicacion: "El financiamiento PUBLICO prevalece sobre el PRIVADO. Siempre. Esta regla no admite excepciones segun el articulo 41 base II." },

    { tipo: "concepto", titulo: "Art. 41 Base III — Acceso a Medios", frente: "¿Como acceden los partidos a radio y television durante campanas?", reverso: "EXCLUSIVAMENTE a traves del INE.\n- Ningun partido puede contratar tiempos directamente.\n- El INE administra los tiempos del Estado.\n- Fuera de campana: 50% igualitario / 50% proporcional.\n- En campana: 1/3 igualitario / 2/3 proporcional.\n- Prohibicion ABSOLUTA de contratacion directa." },

    { tipo: "contenido", titulo: "Art. 41 Base IV — El INE", contenido: "<p><b>Definicion constitucional:</b> 'Organismo publico autonomo dotado de personalidad juridica y patrimonio propios.'</p><p><b>No es:</b> dependencia del Ejecutivo, organo del Poder Judicial, organismo de partido.</p><p><b>Consejo General:</b> 11 Consejeros Electorales (incluye al Presidente), designados por la Camara de Diputados por 2/3 partes. Duran 9 anos, sin reeleccion.</p><p><b>Integracion tripartita:</b> ciudadanos (consejeros), partidos (representantes con voz sin voto), Poder Legislativo (designa consejeros).</p>" },

    { tipo: "formula", titulo: "Los 6 Principios Rectores del INE", formula: "C — Certeza\nL — Legalidad\nI — Independencia\nM — Maxima publicidad\nI — Imparcialidad\nO — Objetividad\n\nMnemotecnia: CLI-MIO", explicacion: "El CENEVAL incluye 'eficiencia' o 'transparencia' como trampa. Los principios del articulo 41 son EXACTAMENTE estos seis. Los OPLEs (art. 116) solo tienen 5: sin 'maxima publicidad'." },

    { tipo: "quiz", titulo: "¿Cual NO es principio del INE?", pregunta: "¿Cual de los siguientes NO es un principio rector del INE segun el articulo 41?", opciones: ["A) Certeza.", "B) Eficiencia.", "C) Objetividad."], respuesta: 1, feedbackOk: "Correcto. 'Eficiencia' es un principio de la administracion publica general pero NO esta en el articulo 41. Los 6 principios del INE son: certeza, legalidad, independencia, imparcialidad, maxima publicidad y objetividad.", feedbackError: "Eficiencia es la trampa. El articulo 41 lista exactamente 6 principios: certeza, legalidad, independencia, imparcialidad, maxima publicidad y objetividad. Eficiencia no esta." },

    { tipo: "concepto", titulo: "Articulo 99 — El TEPJF", frente: "¿Que es el TEPJF y donde se ubica en la estructura del Estado?", reverso: "Tribunal Electoral del Poder Judicial de la Federacion.\n- Maxima autoridad JURISDICCIONAL en materia electoral.\n- Forma parte del Poder Judicial (no es autonomo como el INE).\n- Sala Superior (CDMX) + Salas Regionales.\n- 7 Magistrados de la Sala Superior.\n- Excepcion: leyes electorales inconstitucionales van a la SCJN (Art. 105 II)." },

    { tipo: "ejemplo", titulo: "INE vs TEPJF — Diferencia critica", contenido: "<p><b>Pregunta trampa del CENEVAL:</b> ¿Quien resuelve si una ley electoral local es inconstitucional?</p><p><b>Respuesta correcta:</b> La <b>Suprema Corte de Justicia de la Nacion</b> (Art. 105 fraccion II), NO el TEPJF.</p><p><b>Regla de oro:</b></p><ul><li>Acto electoral impugnado → <b>TEPJF</b></li><li>Ley electoral inconstitucional → <b>SCJN</b></li><li>Organizacion y administracion electoral → <b>INE</b></li></ul>" },

    { tipo: "contenido", titulo: "Articulo 116 Fraccion IV — Los OPLEs", contenido: "<p>Los estados deben garantizar en sus leyes electorales:</p><ul><li>Partidos constituidos SOLO por ciudadanos (sin sindicatos, empresas o iglesias)</li><li>Financiamiento publico prevalece sobre privado</li><li>Acceso a medios SOLO por el INE (mismas reglas del Art. 41 Base III)</li><li>OPLEs con autonomia, personalidad juridica y patrimonio propios</li><li>Consejeros designados por el <b>Consejo General del INE</b></li><li>7 consejeros por OPLE: 1 presidente + 6 consejeros electorales</li></ul>" },

    { tipo: "quiz", titulo: "¿Quien designa a los consejeros de los OPLEs?", pregunta: "Segun el articulo 116 fraccion IV, los consejeros de los Organismos Publicos Locales Electorales son designados por:", opciones: ["A) El gobernador del estado con aprobacion del congreso local.", "B) El Consejo General del INE.", "C) La Camara de Diputados federal."], respuesta: 1, feedbackOk: "Correcto. Desde la reforma de 2014, el Consejo General del INE designa a los consejeros de todos los OPLEs del pais. Esto garantiza su independencia frente a poderes politicos locales.", feedbackError: "Antes de 2014 los designaban los congresos locales (lo que generaba capturas politicas). La reforma de 2014 modifico el Art. 116 para que sea el Consejo General del INE quien los designe." },

    { tipo: "concepto", titulo: "INE (11) vs OPLE (7) — No los confundas", frente: "¿Cuantos consejeros tiene el Consejo General del INE y cuantos tiene un OPLE?", reverso: "INE: 11 Consejeros Electorales (incluye al Consejero Presidente)\nOPLE: 7 consejeros (1 presidente + 6 consejeros electorales)\n\nAmbos: designados por el Consejo General del INE\nAmbos duran en cargo segun ley (INE = 9 anos)\nTrampa del CENEVAL: invertir los numeros" },

    { tipo: "resumen", titulo: "Puntos clave del Dia 21", puntos: ["Art. 39: Soberania reside ESENCIAL y ORIGINARIAMENTE en el pueblo.", "Art. 40: Republica REPRESENTATIVA, DEMOCRATICA, LAICA y FEDERAL (en ese orden).", "Art. 41: INE = organismo publico autonomo. Partidos = entidades de interes publico. Financiamiento publico prevalece. Medios SOLO por INE.", "Principios del INE (6): certeza, legalidad, independencia, imparcialidad, maxima publicidad, objetividad.", "Art. 99: TEPJF = maxima autoridad JURISDICCIONAL electoral. SCJN resuelve inconstitucionalidad de leyes electorales.", "Art. 116: OPLEs con 7 consejeros designados por el Consejo General del INE.", "Manana: Arts. 34-35. Ciudadania y derechos politicos."] }

]);
