registerPresentation(20, 'B', 'Cierre Fase A+B: Velocidad y Puente al Modulo C', [
    { tipo: "titulo", modulo: "A+B", titulo: "Cierre Fase A+B: Velocidad y Puente al Modulo C", subtitulo: "Dia 20 -- Tecnicas Express, Series Numericas y Vista Previa del Modulo C" },

    { tipo: "contenido", titulo: "¿Por que hoy es diferente?", contenido: "<p>El Dia 20 cierra 20 dias de Modulos A y B. Hoy no hay tema nuevo: hay <b>conversion de conocimiento en velocidad</b>.</p><ul><li>170 preguntas en 5 horas = 1 min 46 seg por reactivo</li><li>Quien tiene tecnica responde en 30 seg lo que otros tardan 2 min</li><li>El tiempo ahorrado en preguntas faciles se gasta en las dificiles</li><li>Manana comienza el Modulo C: Sistema Electoral y Constitucional</li></ul>" },

    { tipo: "formula", titulo: "Distribucion optima del tiempo", formula: "Modulo A: 60 min | Modulo B: 55 min\nModulo C: 70 min | Modulo D: 75 min\nRevision de banderas: 40 min\nTOTAL: 300 min (5 horas)", explicacion: "Esta distribucion maximiza el tiempo en los modulos mas tecnicos (C y D) que son los que evaluan directamente el puesto de Vocal Secretario." },

    { tipo: "concepto", titulo: "Metodo SONAR para textos", frente: "¿Cuales son los 5 pasos del metodo SONAR para comprension lectora en examen?", reverso: "S = Scan the question first (lee la pregunta antes del texto)\nO = Overview: lee solo 1er y ultimo parrafo\nN = Note the topic sentence de cada parrafo\nA = Answer using ONLY the text\nR = Review tu seleccion contra la pregunta" },

    { tipo: "contenido", titulo: "Los 4 distractores del Modulo A", contenido: "<ul><li><b>Trampa 1 -- Demasiado fuerte:</b> El texto dice 'puede'; la trampa dice 'siempre'. Rechaza opciones con 'siempre', 'nunca', 'todos', 'ninguno' salvo que el texto lo diga explicitamente.</li><li><b>Trampa 2 -- Fuera del texto:</b> Afirmacion verdadera en la realidad pero no apoyada por el texto. El texto es tu unico universo.</li><li><b>Trampa 3 -- Inversion causal:</b> El texto dice 'A causa B'; la trampa dice 'B causa A'.</li><li><b>Trampa 4 -- Parcialmente correcta:</b> Si un elemento de la opcion es incorrecto, toda la opcion es incorrecta.</li></ul>" },

    { tipo: "quiz", titulo: "Aplica el metodo SONAR", pregunta: "Texto: 'La democracia representativa no se agota en el voto. Requiere que los representantes rindan cuentas de manera continua y que los ciudadanos cuenten con mecanismos para exigir esa rendicion.' ¿Cual es la idea principal?", opciones: ["A) La democracia requiere elecciones libres y periodicas.", "B) La representacion democratica exige tanto el voto como mecanismos de rendicion de cuentas.", "C) La rendicion de cuentas es mas importante que el derecho al voto."], respuesta: 1, feedbackOk: "Correcto. El texto equilibra ambos elementos: no dice que uno sea mas importante (elimina C), y no se limita al voto (elimina A). La tesis completa requiere los dos.", feedbackError: "Aplica el paso A de SONAR: responde SOLO con el texto. El texto no dice que el voto sea 'libre y periodico' (A) ni que la rendicion sea 'mas importante' (C). Solo dice que ambos son necesarios (B)." },

    { tipo: "formula", titulo: "Regla anti-dequeismo en 15 segundos", formula: "Prueba: sustituye el verbo por 'OPINAR'\n¿'Opino de que...'? Suena mal = el DE sobra (dequeismo)\n¿'Opino que...'? Suena bien = el verbo NO pide DE", explicacion: "Confirmo de que / Señalo de que / Digo de que -- todos son dequeismo. El verbo 'confirmar', 'señalar', 'decir' no admiten DE antes de QUE." },

    { tipo: "concepto", titulo: "Laismo: la trampa mas frecuente", frente: "¿Como distinguir si el pronombre debe ser 'le' o 'la' en una oracion?", reverso: "Pregunta: ¿el pronombre sustituye a alguien que RECIBE la accion (CI) o a quien ES la accion (CD)?\nCI = 'a quien se lo dije/envie/comunique' = LE/LES\nCD = 'a quien VI/LLAME/LLEVE' = LA/LAS\nLaismo = usar LA como CI. Siempre incorrecto." },

    { tipo: "formula", titulo: "5 tipos de series numericas", formula: "1. ARITMETICA: diferencia constante (calcula 2 diferencias)\n2. GEOMETRICA: cociente constante (calcula 2 cocientes)\n3. DE DIFERENCIAS: las diferencias forman otra serie\n4. ENTRELAZADA: separa pares e impares\n5. COMBINADA: patron mixto (x2+1, x3-2, etc.)", explicacion: "Antes de calcular, IDENTIFICA el tipo. Eso ahorra 30 segundos por serie." },

    { tipo: "ejemplo", titulo: "Serie de diferencias -- paso a paso", contenido: "<p><b>Serie:</b> 3, 4, 6, 9, 13, 18, ___</p><p><b>Paso 1:</b> Calcula diferencias: 1, 2, 3, 4, 5</p><p><b>Paso 2:</b> ¿Son constantes? No. ¿Forman una serie? Si: +1 cada vez.</p><p><b>Paso 3:</b> Siguiente diferencia = 6</p><p><b>Resultado:</b> 18 + 6 = <b>24</b></p><p class='nota'>Tiempo optimo: 35 segundos</p>" },

    { tipo: "quiz", titulo: "Serie entrelazada", pregunta: "¿Cual es el siguiente numero? 1, 4, 2, 8, 4, 16, 8, ___", opciones: ["A) 12", "B) 32", "C) 16"], respuesta: 1, feedbackOk: "¡Exacto! Posiciones impares: 1, 2, 4, 8 (razon x2). Posiciones pares: 4, 8, 16 (razon x2). Posicion 8 es par: 16 x 2 = 32.", feedbackError: "No hay patron en todos los terminos juntos. Separa: impares (1,2,4,8) y pares (4,8,16). Ambas son geometricas x2. El siguiente es par (posicion 8): 16 x 2 = 32." },

    { tipo: "formula", titulo: "Proporcion directa vs inversa", formula: "DIRECTA: si A sube, B tambien sube\n  a/b = c/d --> a*d = b*c\nINVERSA: si A sube, B baja\n  a*b = c*d (producto constante)\nTEST: 'si hay mas X, hay mas/menos Y?'", explicacion: "Mas funcionarios -> mas boletas (DIRECTA). Mas funcionarios -> menos dias (INVERSA). El test logico nunca falla." },

    { tipo: "ejemplo", titulo: "Regla de tres compuesta", contenido: "<p><b>Situacion:</b> 6 supervisores procesan 480 actas en 4 dias. Si hay 8 supervisores y 3 dias, ¿cuantas actas?</p><p><b>Variable 1 (supervisores):</b> 6 a 8, sube --> efecto directo: x(8/6)</p><p><b>Variable 2 (dias):</b> 4 a 3, baja --> efecto directo: x(3/4)</p><p><b>Resultado:</b> 480 x (8/6) x (3/4) = 480 x 24/24 = 480 x 1 = <b>480 actas</b></p><p>Los efectos se cancelan: un factor mas de supervisores compensa un dia menos.</p>" },

    { tipo: "quiz", titulo: "Proporcion en contexto electoral", pregunta: "El 40% de los votos validos de una casilla fueron para el Partido B, que obtuvo 320 votos. ¿Cuantos votos validos hubo en total?", opciones: ["A) 640 votos", "B) 800 votos", "C) 880 votos"], respuesta: 1, feedbackOk: "Correcto. 320 = 40% del total. Total = 320 / 0.40 = 800. Verificacion: 800 x 0.40 = 320. ✔", feedbackError: "Si 320 = 40% del total, entonces Total = 320 / 0.40 = 800. La trampa A seria si confundes y calculas 320 x 2 = 640 (que seria el 100% si 40% fuera 50%, lo cual es incorrecto)." },

    { tipo: "contenido", titulo: "Puente al Modulo C: Los 5 articulos clave", contenido: "<p><b>Manana empieza la Fase 2.</b> Los articulos imprescindibles:</p><ul><li><b>Art. 39:</b> Soberania nacional reside en el pueblo</li><li><b>Art. 40:</b> Republica representativa, democratica, laica y federal</li><li><b>Art. 41:</b> El INE, partidos politicos y proceso electoral (EL MAS IMPORTANTE)</li><li><b>Art. 99:</b> Tribunal Electoral del PJF (TEPJF)</li><li><b>Art. 116:</b> Sistema electoral de los estados</li></ul>" },

    { tipo: "concepto", titulo: "La tecnica de banderas", frente: "¿Que hacer cuando un reactivo te toma mas de 90 segundos sin respuesta clara?", reverso: "1. ELIMINA las opciones que sabes que son incorrectas\n2. MARCA tu mejor estimado en la hoja de respuestas\n3. SEÑALA el numero del reactivo para revisarlo\n4. SIGUE adelante sin mirar atras\nNUNCA dejes en blanco: sin penalizacion por error, siempre es mejor marcar." },

    { tipo: "resumen", titulo: "Puntos clave del Dia 20", puntos: ["Metodo SONAR: lee la pregunta ANTES del texto para activar lectura dirigida.", "4 distractores CENEVAL: demasiado fuerte, fuera del texto, inversion causal, parcialmente correcto.", "Series: identifica el tipo (aritmetica/geometrica/diferencias/entrelazada) antes de calcular.", "Proporciones: test logico para distinguir directa e inversa; regla de tres compuesta multiplica factores.", "Tecnica de banderas: nunca dejar en blanco; marcar mejor estimado y revisar al final.", "Manana: Modulo C -- Art. 41 constitucional, el INE y el proceso electoral."] }
]);
