registerPresentation(18, 'A', 'Inferencia Critica y Porcentajes Encadenados', [
    { tipo: "titulo", modulo: "A+B", titulo: "Inferencia Critica y Porcentajes Encadenados", subtitulo: "Dia 18 — Nivel Maximo de Precision bajo Presion de Tiempo" },
    { tipo: "contenido", titulo: "Objetivo del Dia 18", contenido: "<p>Hoy dominamos las dos habilidades mas diferenciadas del examen SPEN:</p><ul><li><b>Modulo A:</b> Nivel critico de comprension lectora — posturas, supuestos implicitos y debilitamiento de argumentos</li><li><b>Modulo B:</b> Porcentajes encadenados — multiplicar factores, nunca sumar porcentajes</li><li>Ejercicios cronometrados para consolidar velocidad de respuesta</li></ul>" },
    { tipo: "concepto", titulo: "Nivel Critico — La regla fundamental", frente: "¿Que distingue al nivel critico del nivel inferencial en comprension lectora?", reverso: "El nivel inferencial deduce lo que el texto implica. El nivel critico EVALUA: posturas del autor, argumentos, supuestos implicitos. Pero siempre con base en el texto — nunca con conocimiento externo." },
    { tipo: "contenido", titulo: "Los 5 Tipos de Preguntas Criticas", contenido: "<ol><li><b>Postura del autor:</b> ¿Con que estaria de acuerdo?</li><li><b>Argumento central:</b> ¿Que tesis defiende?</li><li><b>Funcion retorica:</b> ¿Para que sirve este parrafo/ejemplo?</li><li><b>Supuesto implicito:</b> ¿Que da por sentado el autor?</li><li><b>Debilitamiento/Fortalecimiento:</b> ¿Que atacaria o apoyaria su argumento?</li></ol>" },
    { tipo: "concepto", titulo: "El Supuesto Implicito", frente: "¿Como identificar el supuesto implicito de un argumento?", reverso: "Toma la conclusion del autor y pregunta: '¿Que tiene que ser verdad para que esta conclusion se sostenga?' Esa premisa no declarada es el supuesto implicito." },
    { tipo: "ejemplo", titulo: "Supuesto Implicito en Contexto Electoral", contenido: "<p><b>Texto:</b> 'La autonomia del INE es una garantia ciudadana. Cuando el organismo electoral depende del poder que gobierna, las decisiones electorales dejan de ser imparciales.'</p><p><b>Supuesto implicito:</b> La imparcialidad del organismo electoral depende de su independencia del poder gobernante.</p><p><b>Trampa:</b> 'El INE actual no es imparcial' — el texto no hace esa afirmacion sobre el INE actual.</p>" },
    { tipo: "quiz", titulo: "Identifica el Supuesto", pregunta: "Texto: 'Sin financiamiento publico equitativo, los partidos con mayor respaldo economico privado siempre tendran ventaja electoral.' ¿Cual es el supuesto implicito?", opciones: ["A) El dinero privado siempre corrompe a los partidos politicos.", "B) La equidad en recursos es condicion necesaria para la competencia electoral justa.", "C) El financiamiento publico elimina por completo las desigualdades electorales."], respuesta: 1, feedbackOk: "Correcto. El autor asume que la equidad de recursos es condicion para la equidad electoral — eso es lo que hace valido su argumento.", feedbackError: "La A generaliza demasiado (el texto no habla de corrupcion). La C es demasiado fuerte. El supuesto es B: la equidad de recursos es condicion necesaria." },
    { tipo: "formula", titulo: "La Trampa del Debilitamiento", formula: "Para DEBILITAR un argumento:\nAtacar su premisa mas importante\nO introducir una excepcion que el autor ignoro", explicacion: "Ejemplo: Si el texto afirma que la RP causa paralisis legislativa, la mejor forma de debilitarlo es mostrar paises con RP que NO tienen paralisis (contradice la premisa). No sirve hablar de otros sistemas." },
    { tipo: "contenido", titulo: "Las 4 Trampas del CENEVAL en Nivel Critico", contenido: "<ul><li><b>Trampa 1 — Respuesta demasiado fuerte:</b> El texto dice 'importante', la trampa dice 'imprescindible' o 'imposible sin'.</li><li><b>Trampa 2 — Fuera del texto:</b> Informacion correcta pero no incluida en el texto.</li><li><b>Trampa 3 — Inversion causal:</b> El texto dice 'A causa B'; la trampa invierte: 'B causa A'.</li><li><b>Trampa 4 — Generalizacion excesiva:</b> El texto habla de un caso; la trampa dice 'siempre' o 'todos'.</li></ul>" },
    { tipo: "formula", titulo: "Porcentajes Encadenados — Regla de Oro", formula: "Factor total = (1 + p1/100) x (1 + p2/100) x ...\nVariacion total = (Factor total - 1) x 100\nPara baja: usar (1 - p/100)", explicacion: "NUNCA sumes los porcentajes directamente. Ejemplo: +20% y luego +15% NO es +35%. Es 1.20 x 1.15 = 1.38 = +38%." },
    { tipo: "ejemplo", titulo: "El Error que Cuesta el Punto", contenido: "<p><b>Situacion:</b> Presupuesto inicial: $3,600,000. Sube 20% en 2024. Baja 15% en 2025.</p><p><b>Trampa:</b> 20% - 15% = 5% → $3,600,000 x 1.05 = $3,780,000 ❌</p><p><b>Correcto:</b><br>2024: $3,600,000 x 1.20 = $4,320,000<br>2025: $4,320,000 x 0.85 = $3,672,000 ✔</p><p>Diferencia: $108,000. El CENEVAL pone las dos como opciones adyacentes.</p>" },
    { tipo: "quiz", titulo: "Calculo Rapido", pregunta: "El numero de casillas activas en un distrito fue de 500. Aumento 10% el primer periodo y disminuyo 10% el segundo. ¿Cuantas casillas hay al final?", opciones: ["A) 500 (igual que al inicio)", "B) 495", "C) 490"], respuesta: 1, feedbackOk: "¡Exacto! 500 x 1.10 = 550. 550 x 0.90 = 495. El +10% y -10% NO se cancelan porque el segundo se aplica sobre una base mayor.", feedbackError: "La trampa es pensar que +10% y -10% se cancelan. 500 x 1.10 = 550. 550 x 0.90 = 495. Siempre calcula paso a paso." },
    { tipo: "concepto", titulo: "Calculo Inverso — Valor Original", frente: "El presupuesto aumento 30% y llego a $1,170. ¿Como encuentras el valor original?", reverso: "DIVIDE entre el factor: 1170 / 1.30 = 900. NUNCA restes el 30% del valor final (1170 x 0.70 = 819 es incorrecto). El porcentaje se aplico sobre la base anterior, no sobre el valor final." },
    { tipo: "quiz", titulo: "Valor Original", pregunta: "Despues de dos aumentos consecutivos del 10% cada uno, el numero de secciones electorales llego a 1,331. ¿Cuantas habia originalmente?", opciones: ["A) 1,100", "B) 1,210", "C) 1,050"], respuesta: 0, feedbackOk: "Correcto. Factor: 1.10 x 1.10 = 1.21. Original: 1331 / 1.21 = 1100. Verificacion: 1100 x 1.21 = 1331. ✔", feedbackError: "Calcula el factor encadenado: 1.10 x 1.10 = 1.21. Luego divide: 1331 / 1.21 = 1100." },
    { tipo: "contenido", titulo: "Puntos Porcentuales vs Variacion Porcentual", contenido: "<p><b>Puntos porcentuales:</b> Diferencia ARITMETICA entre dos porcentajes.<br>Si la participacion sube de 58% a 69.6%, sube <b>11.6 puntos porcentuales</b>.</p><p><b>Variacion porcentual:</b> Cambio RELATIVO del propio porcentaje.<br>(11.6 / 58) x 100 = 20% de variacion porcentual.</p><p class='nota'>El CENEVAL usa ambas formulaciones. Lee la pregunta con atencion.</p>" },
    { tipo: "ejemplo", titulo: "Porcentaje de Porcentaje", contenido: "<p><b>Situacion:</b> De 4,500 militantes, el 40% son mujeres. De ellas, el 35% tienen 18-30 anos.</p><p><b>Militantes jovenes:</b> 4500 x 0.40 x 0.35 = 4500 x 0.14 = <b>630</b></p><p>Atajo: multiplica los porcentajes como decimales en una sola operacion.</p>" },
    { tipo: "resumen", titulo: "Puntos clave del Dia 18", puntos: ["Nivel critico: siempre con base en el texto, nunca con conocimiento externo.", "5 tipos de preguntas criticas: postura, argumento, funcion, supuesto, debilitamiento.", "4 trampas CENEVAL: demasiado fuerte, fuera del texto, inversion causal, generalizacion excesiva.", "Porcentajes encadenados: MULTIPLICAR factores, nunca sumar porcentajes.", "Calculo inverso: DIVIDIR entre el factor, nunca restar el % del valor final.", "Puntos porcentuales (diferencia) ≠ Variacion porcentual (cambio relativo)."] }
]);
