registerPresentation(22, 'C', 'Ciudadania y Derechos Politicos (Arts. 34 y 35)', [

    { tipo: "titulo", modulo: "C", titulo: "Ciudadania y Derechos Politicos", subtitulo: "Dia 22 — Articulos 34 y 35 CPEUM: ¿Quien es ciudadano y cuales son sus derechos?" },

    { tipo: "contenido", titulo: "La cadena juridica hacia la ciudadania", contenido: "<p>La Constitucion construye una cadena logica de mayor a menor especificidad:</p><ul><li><b>Persona (Art. 1):</b> cualquier ser humano en Mexico tiene derechos humanos.</li><li><b>Nacional (Art. 30):</b> mexicano por nacimiento o naturalizacion — pertenencia al Estado.</li><li><b>Ciudadano (Art. 34):</b> nacional + 18 anos + modo honesto de vivir — PARTICIPACION POLITICA.</li></ul><p>Todo ciudadano es nacional, pero no todo nacional es ciudadano. Un nino de 10 anos es nacional pero no ciudadano.</p>" },

    { tipo: "concepto", titulo: "Articulo 34 — Los DOS requisitos", frente: "¿Cuantos requisitos establece el articulo 34 para la ciudadania?", reverso: "DOS requisitos (no tres):\n\nFraccion I: Haber cumplido DIECIOCHO anos.\nFraccion II: Tener un MODO HONESTO DE VIVIR.\n\nPresupuesto (no requisito): ser mexicano.\n\nTrampa CENEVAL: presentar 'ser mexicano' como tercer requisito." },

    { tipo: "formula", titulo: "Art. 34 — Nacionalidad vs Ciudadania", formula: "NACIONALIDAD (Art. 30)\n+ 18 anos cumplidos\n+ Modo honesto de vivir\n= CIUDADANIA (Art. 34)\n\nMexicano por nacimiento: nunca pierde la nacionalidad.\nMexicano por naturalizacion: puede perderla (Art. 37).\nPadron: trámite desde 17 anos 6 meses (LGIPE).", explicacion: "El INE no verifica el 'modo honesto de vivir' con una certificacion formal. Se materializa a traves de la suspension del Art. 38 cuando hay conductas contrarias." },

    { tipo: "contenido", titulo: "Art. 35 — Los 9 derechos del ciudadano", contenido: "<p>El articulo 35 establece un catalogo de <b>9 fracciones</b>:</p><ul><li><b>Fr. I:</b> Votar en elecciones populares (voto ACTIVO).</li><li><b>Fr. II:</b> Poder ser votado — candidaturas + independientes (voto PASIVO).</li><li><b>Fr. III:</b> Asociarse individual y libremente en forma pacifica.</li><li><b>Fr. IV:</b> Tomar las armas en el Ejercito o Guardia Nacional.</li><li><b>Fr. V:</b> Derecho de peticion en toda clase de negocios.</li><li><b>Fr. VI:</b> Ser nombrado para empleos del servicio publico.</li><li><b>Fr. VII:</b> Iniciativa popular (0.13% del padron).</li><li><b>Fr. VIII:</b> Votar en consultas populares.</li><li><b>Fr. IX:</b> Votar en revocacion de mandato.</li></ul>" },

    { tipo: "concepto", titulo: "Voto activo vs. voto pasivo", frente: "¿Cual es la diferencia entre las fracciones I y II del articulo 35?", reverso: "Fr. I — VOTO ACTIVO: derecho de EMITIR sufragio para elegir representantes.\nCaracteristicas (Art. 41): universal, libre, secreto y directo.\n\nFr. II — VOTO PASIVO: derecho de SER VOTADO, ser candidato.\nIncluye candidaturas independientes (reforma 2012).\nLas 'calidades' adicionales las fija la ley secundaria (LGIPE)." },

    { tipo: "quiz", titulo: "Test Art. 35 Fr. II", pregunta: "Un ciudadano quiere registrarse como candidato independiente a diputado federal. ¿Que fraccion del articulo 35 ampara su derecho?", opciones: ["A) Fraccion I (votar en elecciones populares).", "B) Fraccion II (poder ser votado, incluyendo candidaturas independientes).", "C) Fraccion III (asociarse libremente en asuntos politicos)."], respuesta: 1, feedbackOk: "Correcto. La Fr. II reconoce el derecho 'a poder ser votado para todos los cargos de eleccion popular' y expresamente menciona el registro de candidatos independientes.", feedbackError: "La Fr. I es el voto ACTIVO (emitir sufragio). La Fr. III es la asociacion politica. El voto PASIVO (ser candidato) es la Fr. II." },

    { tipo: "formula", titulo: "Los 3 porcentajes criticos del Art. 35", formula: "INICIATIVA POPULAR (Fr. VII): 0.13% del padron\n→ Proponer leyes al Congreso\n\nCONSULTA POPULAR (Fr. VIII): 2% del padron para convocarla\n→ Tema de trascendencia nacional\n→ VINCULANTE si participa el 40%\n\nREVOCACION DE MANDATO (Fr. IX): 33% del padron\n→ Solo el Presidente, desde el 3er ano\n→ VINCULANTE si participa el 40%", explicacion: "Mneotecnia: 0.13 - 2 - 33. Iniciativa es la mas accesible (menos firmas). Revocacion es la mas exigente (33%). CENEVAL los mezcla constantemente." },

    { tipo: "ejemplo", titulo: "Ejemplo de calculo: Consulta Popular", contenido: "<p><b>Escenario:</b> Padron = 98,000,000 ciudadanos. Ciudadanos reunen 2,500,000 firmas y solicitan consulta popular sobre construccion de un aeropuerto.</p><p><b>Analisis:</b></p><ul><li>2% de 98,000,000 = 1,960,000. Tienen 2,500,000 → <b>SI cumplen el minimo.</b></li><li>El tema (aeropuerto) no es materia electoral ni esta en las 7 exclusiones → <b>SI procede.</b></li><li>Si participan 40,000,000 votantes: 40% de 98M = 39.2M. 40M > 39.2M → <b>VINCULANTE.</b></li><li>Si participan 35,000,000: 35M < 39.2M → <b>NO vinculante (solo orientador).</b></li></ul>" },

    { tipo: "concepto", titulo: "Las 7 materias excluidas de la consulta popular", frente: "¿Que materias NO pueden ser objeto de consulta popular segun el Art. 35 Fr. VIII?", reverso: "1. Restriccion de derechos humanos reconocidos por la CPEUM.\n2. Principios del Art. 40 (republica representativa, democratica, laica y federal).\n3. Permanencia de servidores publicos de eleccion popular.\n4. MATERIA ELECTORAL (trampa clasica del CENEVAL).\n5. Ingresos y gastos del Estado.\n6. Seguridad nacional.\n7. Organizacion y disciplina de la Fuerza Armada." },

    { tipo: "quiz", titulo: "¿Procede la consulta popular?", pregunta: "Ciudadanos con el 3% del padron proponen una consulta para reformar la ley electoral. ¿Procede?", opciones: ["A) Si, porque superan el 2% minimo requerido.", "B) No, porque la materia electoral esta expresamente excluida.", "C) Si, pero requieren adicionalmente la aprobacion del Congreso."], respuesta: 1, feedbackOk: "Correcto. La materia electoral es una de las 7 materias constitucionalmente excluidas. No importa cuantas firmas tengan: el objeto de la consulta es inconstitucional.", feedbackError: "El numero de firmas no es el unico requisito. La Constitucion excluye expresamente la materia electoral. Con cualquier porcentaje de firmas, esta consulta seria improcedente." },

    { tipo: "formula", titulo: "Revocacion de mandato vs. Consulta Popular", formula: "CONSULTA POPULAR:\n¿Quien convoca? Presidente / Congreso / 2% ciudadanos\n¿Sobre que? Cualquier tema (excepto 7 exclusiones)\n¿Cuando? En cualquier momento\n\nREVOCACION DE MANDATO:\n¿Quien convoca? SOLO ciudadanos (33% del padron)\n¿Sobre que? SOLO el mandato del Presidente federal\n¿Cuando? A partir del 3er ano del sexenio", explicacion: "Diferencia clave: la revocacion solo la pueden convocar los ciudadanos (no el Presidente ni el Congreso) y solo aplica al Presidente federal, a partir del tercer ano." },

    { tipo: "contenido", titulo: "Articulo 38 — Suspension de derechos", contenido: "<p>La suspension es <b>TEMPORAL</b> (no es perdida). Las causales son:</p><ul><li><b>Fr. II:</b> Estar sujeto a proceso criminal — desde el <b>AUTO DE FORMAL PRISION</b> (no desde la sentencia).</li><li><b>Fr. III:</b> Durante la extincion de una pena corporal (mientras esta en prision).</li><li><b>Fr. IV:</b> Vagancia o ebriedad consuetudinaria declarada.</li><li><b>Fr. V:</b> Ser prófugo de la justicia — desde la orden de aprehension.</li><li><b>Fr. VI:</b> Sentencia que imponga la suspension como pena accesoria.</li></ul><p><b>Al cesar la causa, los derechos se recuperan automaticamente.</b></p>" },

    { tipo: "concepto", titulo: "Auto de formal prision — trampa del examen", frente: "¿Desde que momento se suspenden los derechos por proceso penal segun el Art. 38 Fr. II?", reverso: "Desde la fecha del AUTO DE FORMAL PRISION.\nNO desde la sentencia condenatoria.\nNO desde la detencion.\n\nEl auto de formal prision es la resolucion judicial que ordena continuar el proceso penal.\nLa presuncion de inocencia (Art. 20 penal) coexiste con la suspension politica.\nAl absolverte o al cumplir condena: derechos recuperados." },

    { tipo: "ejemplo", titulo: "Caso practico: ciudadano con proceso penal", contenido: "<p><b>Caso:</b> Rosa fue detenida el 1 de enero. El juez dicto auto de formal prision el 10 de enero. El juicio concluyo el 15 de junio con absolucion. Las elecciones son el 2 de junio.</p><p><b>Analisis:</b></p><ul><li>Del 10 de enero al 2 de junio: derechos suspendidos por Art. 38 Fr. II → <b>NO puede votar el 2 de junio.</b></li><li>El 15 de junio es absuelta: derechos recuperados.</li><li>Si hubiera elecciones el 1 de julio: <b>SI podria votar.</b></li></ul><p>La presuncion de inocencia no evita la suspension politica. Solo la resolucion o cumplimiento de la pena la levanta.</p>" },

    { tipo: "quiz", titulo: "Test suspension de derechos", pregunta: "Ana cumplio una pena privativa de libertad hace 2 anos. Sus derechos fueron suspendidos durante la condena. ¿Puede votar hoy?", opciones: ["A) No, porque los antecedentes penales implican suspension permanente.", "B) Si, porque la suspension termino al cumplir la condena y sus derechos se recuperaron.", "C) Solo si el juez emite una resolucion expresa de restitucion de derechos."], respuesta: 1, feedbackOk: "Correcto. La suspension del Art. 38 es temporal. Al cumplir la condena, los derechos se recuperan automaticamente. No se requiere resolucion judicial adicional para ello.", feedbackError: "La suspension de derechos del Art. 38 es temporal, no permanente. Los antecedentes penales por si solos no mantienen suspendidos los derechos una vez cumplida la condena." },

    { tipo: "contenido", titulo: "Conexion con el rol del Vocal Secretario", contenido: "<p>Los Arts. 34-38 son el fundamento operativo diario del Vocal Secretario:</p><ul><li><b>Padron electoral:</b> gestionar la inscripcion de ciudadanos que cumplen Art. 34 (trámite desde 17a6m).</li><li><b>Lista nominal:</b> depurar ciudadanos con derechos suspendidos (Art. 38).</li><li><b>Candidaturas:</b> verificar que los aspirantes tengan derechos en ejercicio (Art. 35 Fr. II).</li><li><b>Funcionarios de casilla:</b> seleccionar ciudadanos con derechos activos (Art. 36).</li><li><b>Consultas y revocacion:</b> organizar operativamente estos procesos en el distrito.</li></ul>" },

    { tipo: "resumen", titulo: "Puntos clave del Dia 22", puntos: ["Art. 34: DOS requisitos (no tres): 18 anos + modo honesto de vivir. Ser mexicano es presupuesto.", "Art. 35 tiene 9 fracciones. Las mas preguntadas: I (votar), II (ser votado + candidaturas independientes), VII (0.13% iniciativa), VIII (2% consulta popular / 40% vinculante), IX (33% revocacion / desde ano 3 / 40% vinculante).", "Materia electoral EXCLUIDA de consulta popular — trampa clasica del CENEVAL.", "Consulta popular: tres convocantes (Pdte/Congreso/2% ciudadanos). Revocacion: SOLO ciudadanos (33%).", "Art. 38: suspension TEMPORAL desde el AUTO DE FORMAL PRISION (no desde la sentencia).", "Diferencia suspension (Art. 38, temporal) vs. perdida de nacionalidad (Art. 37, solo naturalizados).", "Manana: Dia 23 — El INE: Consejo General y Junta General Ejecutiva."] }

]);
